---
abstract: 'A simple domain-specific language for role-playing game tools'
author:
  - 'Paul M. Lambert <plambert@plambert.net>'
build_requires:
  File::ChangeNotify: '0.24'
  JSON: '2.90'
  MooseX::SemiAffordanceAccessor: '0.10'
  Spiffy: '0.46'
  Test::Base: '0.88'
  Test::Continuous: '0.76'
  Test::LongString: '0.17'
  Test::More: '1.001014'
  Test::YAML: '1.06'
  Text::Diff: '1.43'
  YAML: '1.15'
configure_requires:
  Module::Build: '0.4214'
dynamic_config: 0
generated_by: 'Module::Build version 0.4214, CPAN::Meta::Converter version 2.150005'
license: apache
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: ORC
provides:
  ORC:
    file: lib/ORC.pm
    version: '0.30'
  ORC::DieExpression:
    file: lib/ORC/DieExpression.pm
  ORC::DieRoll:
    file: lib/ORC/DieRoll.pm
  ORC::Number:
    file: lib/ORC/Number.pm
  ORC::Operator:
    file: lib/ORC/Operator.pm
  ORC::Operator::Addition:
    file: lib/ORC/Operator/Addition.pm
  ORC::Operator::Division:
    file: lib/ORC/Operator/Division.pm
  ORC::Operator::Multiplication:
    file: lib/ORC/Operator/Multiplication.pm
  ORC::Operator::Subtraction:
    file: lib/ORC/Operator/Subtraction.pm
  ORC::Parser:
    file: lib/ORC/Parser.pm
  ORC::RNG:
    file: lib/ORC/RNG.pm
  ORC::RNG::Mock:
    file: lib/ORC/RNG/Mock.pm
  ORC::RNG::Random:
    file: lib/ORC/RNG/Random.pm
  ORC::Role::RNG:
    file: lib/ORC/Role/RNG.pm
  ORC::Role::Serializable:
    file: lib/ORC/Role/Serializable.pm
  ORC::Script:
    file: lib/ORC/Script.pm
  ORC::Statement::Assignment:
    file: lib/ORC/Statement/Assignment.pm
  ORC::Types:
    file: lib/ORC/Types.pm
  ORC::Undef:
    file: lib/ORC/Undef.pm
  ORC::Variable:
    file: lib/ORC/Variable.pm
requires:
  Carp::Always: '0.13'
  Modern::Perl: '1.20150127'
  Moose: '2.1604'
  Parse::RecDescent: '1.967013'
  namespace::sweep: '0.006'
version: '0.30'
x_serialization_backend: 'CPAN::Meta::YAML version 0.017'
